repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
    - id: reorder-python-imports
      args: ["--exit-zero-even-if-changed"]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
      args: ["-v"]
