FROM ubuntu:latest

ARG USER=gary
ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} ${USER} \
 && useradd -u ${UID} -g ${GID} -m ${USER} \
 && mkdir -p /home/${USER}/.vscode-server \
 && chown -R ${UID}:${GID} /home/$USER/ \
 && apt-get update \
 && apt-get install -y git python3.7 python3-pip \
 && cd /usr/bin \
 && ln -s python3 python \
 && rm -rf /var/lib/apt/lists/*

USER $USER

RUN python3.7 -m pip install -U pip --user \
 && python3.7 -m pip install -U pylint autopep8 coverage configobj cherrypy requests pexpect musicbrainzngs gitpython --user
